apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Replace `sealed-secrets.example.yaml` from base with your real SealedSecret here:
# patches:
#   - target: { kind: Secret, name: bitesense-secrets }
#     path: secret-patch.yaml
images:
  - name: ghcr.io/marvinf95/bitesense-backend
    newTag: v0.1.0
  - name: ghcr.io/marvinf95/bitesense-frontend
    newTag: v0.1.0
